[package]
name = "bevy_miniquad"
version = "0.1.0"
authors = ["Tomasz Sterna <tomek@sterna.link>"]
edition = "2018"

[features]
default = ["winit"]
winit = ["bevy/bevy_winit"]

[dependencies]
bevy = { path = "../bevy", default-features = false }
miniquad = { path = "../miniquad" }
log = "0.4"
console_error_panic_hook = "0.1.6"
console_log = "0.2"
