[package]
name = "bevy_miniquad"
version = "0.1.0"
authors = ["Tomasz Sterna <tomek@sterna.link>"]
edition = "2018"

[features]
log-impl = ["miniquad/log-impl"]

[dependencies]
bevy_app = { version = "*", default-features = false }
bevy_input = { version = "*", default-features = false }
bevy_math = { version = "*", default-features = false }
bevy_window = { version = "*", default-features = false }
miniquad = "0.2"
